"""auction realm activity datapoints table

Revision ID: 09368752d130
Revises: 4f201dd47ef2
Create Date: 2025-09-02 09:26:47.011514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09368752d130'
down_revision: Union[str, Sequence[str], None] = '4f201dd47ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_realm_activity_datapoints',
    sa.Column('server_realm_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('total_auctions', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('total_market_value', sa.Integer(), nullable=False),
    sa.Column('estimated_market_value', sa.Integer(), nullable=False),
    sa.Column('datapoint_count', sa.Integer(), nullable=False),
    sa.Column('outlier_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_realm_id'], ['server_realms.id'], ),
    sa.PrimaryKeyConstraint('server_realm_id', 'ts')
    )
    op.create_index('idx_r_realm_ts', 'auction_realm_activity_datapoints', ['server_realm_id', sa.literal_column('ts DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_r_realm_ts', table_name='auction_realm_activity_datapoints')
    op.drop_table('auction_realm_activity_datapoints')
    # ### end Alembic commands ###
