"""realm market activity indexes

Revision ID: 4f201dd47ef2
Revises: de47ad5544da
Create Date: 2025-09-01 21:58:01.741771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f201dd47ef2'
down_revision: Union[str, Sequence[str], None] = 'de47ad5544da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_adp_realm_time_cover_price', 'auction_datapoints', ['server_realm_id', 'timestamp'], unique=False, postgresql_include=('buyout_price', 'quantity'), postgresql_where=sa.text('buyout_price > 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_adp_realm_time_cover_price', table_name='auction_datapoints', postgresql_include=('buyout_price', 'quantity'), postgresql_where=sa.text('buyout_price > 0'))
    # ### end Alembic commands ###
