"""Initial

Revision ID: d7da8731b343
Revises: 
Create Date: 2025-08-30 16:30:07.148758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7da8731b343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_realms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('realm', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server', 'realm', name='uq_server_realms_server_realm')
    )
    op.create_index(op.f('ix_server_realms_id'), 'server_realms', ['id'], unique=False)
    op.create_index(op.f('ix_server_realms_realm'), 'server_realms', ['realm'], unique=False)
    op.create_index(op.f('ix_server_realms_server'), 'server_realms', ['server'], unique=False)
    op.create_index('ix_server_realms_server_realm', 'server_realms', ['server', 'realm'], unique=False)
    op.create_table('auction_datapoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('server_realm_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('buyout_price', sa.Integer(), nullable=False),
    sa.Column('starting_bid_price', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_realm_id'], ['server_realms.id'], ),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_a_item_server_realm_ts', 'auction_datapoints', ['item_id', 'server_realm_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_realm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('max_stack_size', sa.Integer(), nullable=False),
    sa.Column('vendor_price', sa.Integer(), nullable=False),
    sa.Column('class_index', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['server_realm_id'], ['server_realms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_quality'), 'items', ['quality'], unique=False)
    op.create_index('ix_items_server_realm', 'items', ['server_realm_id'], unique=False)
    op.create_index(op.f('ix_items_server_realm_id'), 'items', ['server_realm_id'], unique=False)
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_realm_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('auction_unit_buyout_price', sa.Integer(), nullable=False),
    sa.Column('auction_unit_starting_bid_price', sa.Integer(), nullable=False),
    sa.Column('auction_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['server_realm_id'], ['server_realms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_auction_unit_buyout_price'), 'auctions', ['auction_unit_buyout_price'], unique=False)
    op.create_index(op.f('ix_auctions_auction_unit_starting_bid_price'), 'auctions', ['auction_unit_starting_bid_price'], unique=False)
    op.create_index(op.f('ix_auctions_id'), 'auctions', ['id'], unique=False)
    op.create_index(op.f('ix_auctions_item_id'), 'auctions', ['item_id'], unique=False)
    op.create_index('ix_auctions_item_server_realm', 'auctions', ['item_id', 'server_realm_id'], unique=False)
    op.create_index(op.f('ix_auctions_server_realm_id'), 'auctions', ['server_realm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_server_realm_id'), table_name='auctions')
    op.drop_index('ix_auctions_item_server_realm', table_name='auctions')
    op.drop_index(op.f('ix_auctions_item_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_auction_unit_starting_bid_price'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_auction_unit_buyout_price'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_items_server_realm_id'), table_name='items')
    op.drop_index('ix_items_server_realm', table_name='items')
    op.drop_index(op.f('ix_items_quality'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index('idx_a_item_server_realm_ts', table_name='auction_datapoints')
    op.drop_table('auction_datapoints')
    op.drop_index('ix_server_realms_server_realm', table_name='server_realms')
    op.drop_index(op.f('ix_server_realms_server'), table_name='server_realms')
    op.drop_index(op.f('ix_server_realms_realm'), table_name='server_realms')
    op.drop_index(op.f('ix_server_realms_id'), table_name='server_realms')
    op.drop_table('server_realms')
    # ### end Alembic commands ###
