"""Item and auction composite key changes

Revision ID: de47ad5544da
Revises: d7da8731b343
Create Date: 2025-08-30 16:32:19.392297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de47ad5544da'
down_revision: Union[str, Sequence[str], None] = 'd7da8731b343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints that reference items.id only
    op.drop_constraint('auctions_item_id_fkey', 'auctions', type_='foreignkey')
    
    # Drop existing primary key constraint on items
    op.drop_constraint('items_pkey', 'items', type_='primary')
    
    # Create new composite primary key on items
    op.create_primary_key('items_pkey', 'items', ['id', 'server_realm_id'])
    
    # Create new foreign key constraint that references the composite key
    op.create_foreign_key('auctions_item_id_server_realm_id_fkey', 'auctions', 'items', ['item_id', 'server_realm_id'], ['id', 'server_realm_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the new composite foreign key constraint
    op.drop_constraint('auctions_item_id_server_realm_id_fkey', 'auctions', type_='foreignkey')
    
    # Drop the composite primary key on items
    op.drop_constraint('items_pkey', 'items', type_='primary')
    
    # Recreate the original single-column primary key on items
    op.create_primary_key('items_pkey', 'items', ['id'])
    
    # Recreate the original foreign key constraint
    op.create_foreign_key('auctions_item_id_fkey', 'auctions', 'items', ['item_id'], ['id'])
    
    # ### end Alembic commands ###
